apiVersion: v1
kind: Service
metadata:
    name: emqx
    labels:
      name: emqx
      app: emqx
    namespace: kube-mqtt
      
spec:
    selector:
      name: mqtt
    type: NodePort
    ports:
    - name: mqtt
      nodePort: 31883
      port: 1883
      targetPort: 1883
      protocol: TCP
      
    - name: mqtt-http
      nodePort: 30083
      port: 18083
      targetPort: 18083
      protocol: TCP
