apiVersion: v1
kind: Pod
metadata:
    name: mqtt
    labels: 
        name: emqx
        app: emqx
    namespace: kube-emqx

spec:
    containers:
    - image: emqx/emqx
      name: emqx
      ports:
      - name: mqtt
        containerPort: 1883
      - name: mqtt-http
        containerPort: 18083
